name: Build Check

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - main

# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash
    working-directory: "application"

jobs:
  Dependency-Review:
    if: github.event.pull_request.draft == false && github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1.0.2-beta7
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v5
      - uses: actions/dependency-review-action@v4
  Build-Check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions: {}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1.0.2-beta7
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-node-pnpm
      - name: Run Tests
        run: pnpm test -- --run
      - name: Build
        run: pnpm run build
